#!/bin/sh

mkdir -p test_data
cd test_data
if [ \! -e "Data Files/Aleanne Armor and Clothes 1+2.esp" ]; then
  wget -O ale-clothing-v1-1c.7z 'http://www.fullrest.ru/files/ale-clothing-v1-1c/files?fid=2379' || exit 1
  7z x ale-clothing-v1-1c.7z || exit 1
  rm -rf *.txt *.htm *.7z files "Data Files/*.bsa"
fi
if [ \! -e "Data Files/Glass_Extension 1С.esp" ]; then
  wget -O GlassExtension_1C.rar 'http://www.fullrest.ru/uploads/files/GlassExtension_1C.rar' || exit 1
  unrar x -y GlassExtension_1C.rar || exit 1
  rm -rf *.htm *.rar files "Data Files/Icons" "Data Files/Meshes" "Data Files/Textures"
fi
if [ \! -e "Data Files/Morrowind.esm" ]; then
  echo "Put Morrowind.esm into test_data/Data Files"
  exit 1
fi

rm -rf "Data Files/NPCs"
rm -f "Data Files/A1V1_Hairs.esp"
dd if=/dev/zero of="Data Files/A1V1_Hairs.esp" bs=1 count=0 seek=100K
stack exec -- A1_Necromancy_init || exit 1
res=$(find "Data Files/NPCs" -type f | wc -l)
if [ $res != 2676 ]; then
  echo "$res"
  exit 1
fi
size=$(wc -c < "Data Files/A1V1_Hairs.esp")
if [ $size != 13837 ]; then
  echo $size
  exit 1
fi
echo "All tests passed."
