#!/bin/sh

mkdir -p test_data
cd test_data
if [ \! -e "Data Files/Aleanne Armor and Clothes 1+2.esp" ]; then
  wget -O ale-clothing-v1-1c.7z 'http://www.fullrest.ru/files/ale-clothing-v1-1c/files?fid=2379' || exit 1
  7z x ale-clothing-v1-1c.7z || exit 1
  rm -rf *.txt *.htm *.7z files
fi
if [ \! -e "Data Files/Morrowind.esm" ]; then
  echo "Put Morrowind.esm into test_data/Data Files"
  exit 1
fi

stack exec -- A1_Necromancy_init || exit 1

echo "All tests passed."
